### PR TITLE
Create Hello

### PR DESCRIPTION
**Pull request by Raine-Yang-UofT**
Hi Professor, hope you like this PR :)

### CODE REVIEW

**Comment by exekis** [comment]
lgtm @Raine-Yang-UofT

**Comment by paulgries** [comment]
Ha! I'll use this in class!

**Comment by Raine-Yang-UofT** [comment]
I also wrote a pretty cool story explanation on OOP concepts, check this out:
https://medium.com/@raineyang2005/the-object-oriented-programming-republic-part-i-ii-661fbf4777ca

**Review by paulgries — APPROVED** [review]
What a great message.

**Pull request merged**
